export const SET_TODOLIST = "SET_TODOLIST";
export const INIT_TODOLIST_FAIL = "INIT_TODOLIST_FAIL";
export const INIT_TODOLIST_START = "INIT_TODOLIST_START";
export const ADD_TASK = "ADD_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const COMPLETED_TASK = "COMPLETED_TASK";
export const DISPLAY_FILTERED_TASKS = "DISPLAY_FILTERED_TASKS";
